export interface Therapist {
  id: string
  name: string
  title: string
  qualifications: string[]
  specialties: string[]
  pricePerSession: number
  rating: number
  reviewCount: number
  availableSlots: {
    day: string
    times: string[]
  }[]
  languages: string[]
  bio: string
  image: string
}

export const therapists: Therapist[] = [
  {
    id: "1",
    name: "Dr. Sarah Mitchell",
    title: "Clinical Psychologist",
    qualifications: ["Ph.D. in Clinical Psychology", "Licensed CBT Practitioner", "15+ years experience"],
    specialties: ["Anxiety", "Depression", "Stress Management"],
    pricePerSession: 1500,
    rating: 4.9,
    reviewCount: 234,
    availableSlots: [
      { day: "Monday", times: ["9:00 AM", "11:00 AM", "2:00 PM", "4:00 PM"] },
      { day: "Wednesday", times: ["10:00 AM", "1:00 PM", "3:00 PM"] },
      { day: "Friday", times: ["9:00 AM", "11:00 AM", "2:00 PM"] },
    ],
    languages: ["English", "Hindi", "French"],
    bio: "Dr. Mitchell specializes in helping individuals overcome anxiety and depression using evidence-based approaches. Her warm and empathetic style creates a safe space for healing.",
    image: "/therapists/sarah.jpg",
  },
  {
    id: "2",
    name: "Dr. James Chen",
    title: "Psychiatrist",
    qualifications: ["M.D. in Psychiatry", "Board Certified", "12+ years experience"],
    specialties: ["Mood Disorders", "PTSD", "Medication Management"],
    pricePerSession: 2500,
    rating: 4.8,
    reviewCount: 189,
    availableSlots: [
      { day: "Tuesday", times: ["10:00 AM", "12:00 PM", "3:00 PM"] },
      { day: "Thursday", times: ["9:00 AM", "11:00 AM", "1:00 PM", "4:00 PM"] },
    ],
    languages: ["English", "Tamil", "Kannada"],
    bio: "Dr. Chen combines medication management with therapeutic techniques to provide comprehensive mental health care. He believes in treating the whole person, not just symptoms.",
    image: "/therapists/james.jpg",
  },
  {
    id: "3",
    name: "Dr. Emily Rodriguez",
    title: "Marriage & Family Therapist",
    qualifications: ["Ph.D. in Family Therapy", "LMFT Licensed", "10+ years experience"],
    specialties: ["Couples Therapy", "Family Dynamics", "Communication"],
    pricePerSession: 1200,
    rating: 4.9,
    reviewCount: 312,
    availableSlots: [
      { day: "Monday", times: ["10:00 AM", "2:00 PM", "5:00 PM"] },
      { day: "Tuesday", times: ["9:00 AM", "11:00 AM", "3:00 PM"] },
      { day: "Saturday", times: ["10:00 AM", "12:00 PM", "2:00 PM"] },
    ],
    languages: ["English", "Spanish", "Telugu"],
    bio: "Dr. Rodriguez helps families and couples build stronger connections through improved communication and understanding. She creates a judgment-free zone for all.",
    image: "/therapists/emily.jpg",
  },
  {
    id: "4",
    name: "Dr. Michael Thompson",
    title: "Behavioral Therapist",
    qualifications: ["Psy.D. in Behavioral Psychology", "ABA Certified", "8+ years experience"],
    specialties: ["OCD", "Phobias", "Behavioral Issues"],
    pricePerSession: 1800,
    rating: 4.7,
    reviewCount: 156,
    availableSlots: [
      { day: "Wednesday", times: ["9:00 AM", "11:00 AM", "1:00 PM", "3:00 PM"] },
      { day: "Thursday", times: ["10:00 AM", "2:00 PM", "4:00 PM"] },
      { day: "Friday", times: ["9:00 AM", "12:00 PM"] },
    ],
    languages: ["English", "Hindi", "Marathi"],
    bio: "Dr. Thompson uses proven behavioral techniques to help clients overcome fears, compulsions, and unwanted behaviors. He focuses on practical, actionable strategies.",
    image: "/therapists/michael.jpg",
  },
  {
    id: "5",
    name: "Dr. Aisha Patel",
    title: "Trauma Specialist",
    qualifications: ["Ph.D. in Trauma Psychology", "EMDR Certified", "14+ years experience"],
    specialties: ["Trauma", "PTSD", "Grief & Loss"],
    pricePerSession: 2000,
    rating: 4.9,
    reviewCount: 278,
    availableSlots: [
      { day: "Monday", times: ["11:00 AM", "2:00 PM", "4:00 PM"] },
      { day: "Tuesday", times: ["9:00 AM", "1:00 PM", "3:00 PM"] },
      { day: "Thursday", times: ["10:00 AM", "12:00 PM", "2:00 PM"] },
    ],
    languages: ["English", "Hindi", "Gujarati", "Urdu"],
    bio: "Dr. Patel specializes in trauma recovery using EMDR and other evidence-based approaches. She provides a compassionate space for healing from life's most difficult experiences.",
    image: "/therapists/aisha.jpg",
  },
  {
    id: "6",
    name: "Dr. David Kim",
    title: "Mindfulness Therapist",
    qualifications: ["Ph.D. in Psychology", "MBSR Certified", "9+ years experience"],
    specialties: ["Mindfulness", "Stress", "Work-Life Balance"],
    pricePerSession: 1000,
    rating: 4.8,
    reviewCount: 201,
    availableSlots: [
      { day: "Tuesday", times: ["8:00 AM", "10:00 AM", "4:00 PM", "6:00 PM"] },
      { day: "Wednesday", times: ["9:00 AM", "11:00 AM", "3:00 PM"] },
      { day: "Friday", times: ["10:00 AM", "2:00 PM", "4:00 PM"] },
    ],
    languages: ["English", "Bengali", "Malayalam"],
    bio: "Dr. Kim integrates mindfulness-based approaches with traditional therapy to help clients find balance, reduce stress, and cultivate inner peace in their daily lives.",
    image: "/therapists/david.jpg",
  },
  {
    id: "7",
    name: "Dr. Priya Sharma",
    title: "Child Psychologist",
    qualifications: ["Ph.D. in Child Psychology", "Play Therapy Certified", "11+ years experience"],
    specialties: ["Child Behavior", "ADHD", "Learning Disabilities"],
    pricePerSession: 1600,
    rating: 4.8,
    reviewCount: 198,
    availableSlots: [
      { day: "Monday", times: ["10:00 AM", "12:00 PM", "3:00 PM"] },
      { day: "Wednesday", times: ["9:00 AM", "11:00 AM", "2:00 PM"] },
      { day: "Saturday", times: ["10:00 AM", "12:00 PM"] },
    ],
    languages: ["Hindi", "English", "Punjabi"],
    bio: "Dr. Sharma specializes in child and adolescent mental health, using play therapy and creative approaches to help young minds thrive and overcome behavioral challenges.",
    image: "/therapists/priya.jpg",
  },
  {
    id: "8",
    name: "Dr. Rajesh Nair",
    title: "Addiction Counselor",
    qualifications: ["M.D. in Psychiatry", "Addiction Medicine Certified", "16+ years experience"],
    specialties: ["Substance Abuse", "Addiction Recovery", "Relapse Prevention"],
    pricePerSession: 2200,
    rating: 4.7,
    reviewCount: 145,
    availableSlots: [
      { day: "Tuesday", times: ["9:00 AM", "11:00 AM", "2:00 PM", "5:00 PM"] },
      { day: "Thursday", times: ["10:00 AM", "1:00 PM", "3:00 PM"] },
      { day: "Friday", times: ["9:00 AM", "11:00 AM"] },
    ],
    languages: ["Malayalam", "English", "Tamil", "Hindi"],
    bio: "Dr. Nair brings extensive experience in addiction recovery, combining medical expertise with compassionate counseling to support patients through every stage of their recovery journey.",
    image: "/therapists/rajesh.jpg",
  },
  {
    id: "9",
    name: "Dr. Fatima Khan",
    title: "Clinical Psychologist",
    qualifications: ["Ph.D. in Clinical Psychology", "CBT & DBT Certified", "10+ years experience"],
    specialties: ["Anxiety", "Self-Esteem", "Women's Mental Health"],
    pricePerSession: 1400,
    rating: 4.9,
    reviewCount: 267,
    availableSlots: [
      { day: "Monday", times: ["9:00 AM", "11:00 AM", "3:00 PM"] },
      { day: "Wednesday", times: ["10:00 AM", "1:00 PM", "4:00 PM"] },
      { day: "Friday", times: ["9:00 AM", "12:00 PM", "2:00 PM"] },
    ],
    languages: ["Urdu", "Hindi", "English"],
    bio: "Dr. Khan focuses on women's mental health and self-esteem building, creating a safe and culturally sensitive environment for clients to explore their thoughts and emotions.",
    image: "/therapists/fatima.jpg",
  },
  {
    id: "10",
    name: "Dr. Arjun Reddy",
    title: "Neuropsychologist",
    qualifications: ["Ph.D. in Neuropsychology", "Board Certified", "13+ years experience"],
    specialties: ["Brain Injury Rehab", "Memory Disorders", "Cognitive Assessment"],
    pricePerSession: 2800,
    rating: 4.8,
    reviewCount: 112,
    availableSlots: [
      { day: "Tuesday", times: ["10:00 AM", "2:00 PM"] },
      { day: "Thursday", times: ["9:00 AM", "11:00 AM", "3:00 PM"] },
    ],
    languages: ["Telugu", "English", "Kannada", "Hindi"],
    bio: "Dr. Reddy is a leading neuropsychologist specializing in cognitive rehabilitation and assessment, helping patients recover cognitive functions after brain injuries and neurological conditions.",
    image: "/therapists/arjun.jpg",
  },
  {
    id: "11",
    name: "Dr. Meera Banerjee",
    title: "Clinical Psychologist",
    qualifications: ["Ph.D. in Clinical Psychology", "ACT Certified", "9+ years experience"],
    specialties: ["Anxiety", "Self-Esteem", "Work-Life Balance"],
    pricePerSession: 1300,
    rating: 4.8,
    reviewCount: 210,
    availableSlots: [
      { day: "Monday", times: ["9:00 AM", "11:00 AM", "3:00 PM"] },
      { day: "Thursday", times: ["10:00 AM", "1:00 PM", "4:00 PM"] },
      { day: "Saturday", times: ["10:00 AM", "12:00 PM"] },
    ],
    languages: ["Bengali", "English", "Hindi"],
    bio: "Dr. Banerjee uses Acceptance and Commitment Therapy to help clients overcome anxiety and build self-esteem. She focuses on creating lasting behavioral change through mindfulness and values-based living.",
    image: "/therapists/meera.jpg",
  },
  {
    id: "12",
    name: "Dr. Carlos Fernandez",
    title: "Trauma Specialist",
    qualifications: ["Psy.D. in Clinical Psychology", "EMDR & Somatic Therapy Certified", "11+ years experience"],
    specialties: ["Trauma", "Grief & Loss", "PTSD"],
    pricePerSession: 1900,
    rating: 4.9,
    reviewCount: 176,
    availableSlots: [
      { day: "Tuesday", times: ["9:00 AM", "12:00 PM", "3:00 PM"] },
      { day: "Wednesday", times: ["10:00 AM", "2:00 PM", "5:00 PM"] },
      { day: "Friday", times: ["9:00 AM", "11:00 AM"] },
    ],
    languages: ["Spanish", "English", "French"],
    bio: "Dr. Fernandez is a bilingual trauma specialist who combines EMDR with somatic experiencing to guide clients through healing from deep-seated trauma and grief.",
    image: "/therapists/carlos.jpg",
  },
  {
    id: "13",
    name: "Dr. Ananya Iyer",
    title: "Child Psychologist",
    qualifications: ["Ph.D. in Developmental Psychology", "CBT for Children Certified", "8+ years experience"],
    specialties: ["Child Behavior", "ADHD", "Anxiety"],
    pricePerSession: 1500,
    rating: 4.7,
    reviewCount: 163,
    availableSlots: [
      { day: "Monday", times: ["10:00 AM", "1:00 PM", "4:00 PM"] },
      { day: "Wednesday", times: ["9:00 AM", "11:00 AM"] },
      { day: "Friday", times: ["10:00 AM", "2:00 PM", "4:00 PM"] },
    ],
    languages: ["Tamil", "English", "Malayalam", "Hindi"],
    bio: "Dr. Iyer is passionate about helping children navigate emotional and behavioral challenges. She uses creative, age-appropriate CBT techniques to empower young clients.",
    image: "/therapists/ananya.jpg",
  },
  {
    id: "14",
    name: "Dr. Vikram Desai",
    title: "Addiction Counselor",
    qualifications: ["M.D. in Psychiatry", "Dual Diagnosis Certified", "14+ years experience"],
    specialties: ["Substance Abuse", "Addiction Recovery", "Depression"],
    pricePerSession: 2100,
    rating: 4.8,
    reviewCount: 134,
    availableSlots: [
      { day: "Monday", times: ["9:00 AM", "12:00 PM"] },
      { day: "Wednesday", times: ["10:00 AM", "2:00 PM", "4:00 PM"] },
      { day: "Thursday", times: ["9:00 AM", "11:00 AM", "3:00 PM"] },
    ],
    languages: ["Gujarati", "Hindi", "English", "Marathi"],
    bio: "Dr. Desai combines psychiatric expertise with compassionate counseling to help clients recover from addiction and co-occurring mental health conditions.",
    image: "/therapists/vikram.jpg",
  },
  {
    id: "15",
    name: "Dr. Simran Kaur",
    title: "Marriage & Family Therapist",
    qualifications: ["Ph.D. in Family Psychology", "EFT Certified", "10+ years experience"],
    specialties: ["Couples Therapy", "Family Dynamics", "Women's Mental Health"],
    pricePerSession: 1400,
    rating: 4.9,
    reviewCount: 225,
    availableSlots: [
      { day: "Tuesday", times: ["9:00 AM", "11:00 AM", "3:00 PM"] },
      { day: "Thursday", times: ["10:00 AM", "1:00 PM", "4:00 PM"] },
      { day: "Saturday", times: ["10:00 AM", "12:00 PM", "2:00 PM"] },
    ],
    languages: ["Punjabi", "Hindi", "English"],
    bio: "Dr. Kaur specializes in Emotionally Focused Therapy to help couples and families rebuild trust, deepen bonds, and communicate more effectively.",
    image: "/therapists/simran.jpg",
  },
  {
    id: "16",
    name: "Dr. Laurent Dupont",
    title: "Mindfulness Therapist",
    qualifications: ["Ph.D. in Psychology", "MBCT Certified", "12+ years experience"],
    specialties: ["Mindfulness", "Stress", "Depression"],
    pricePerSession: 1700,
    rating: 4.8,
    reviewCount: 189,
    availableSlots: [
      { day: "Monday", times: ["10:00 AM", "2:00 PM"] },
      { day: "Wednesday", times: ["9:00 AM", "11:00 AM", "3:00 PM"] },
      { day: "Friday", times: ["10:00 AM", "1:00 PM", "4:00 PM"] },
    ],
    languages: ["French", "English", "Spanish"],
    bio: "Dr. Dupont integrates Mindfulness-Based Cognitive Therapy with traditional approaches, helping clients break free from cycles of depression and chronic stress.",
    image: "/therapists/laurent.jpg",
  },
  {
    id: "17",
    name: "Dr. Ritu Malhotra",
    title: "Behavioral Therapist",
    qualifications: ["Psy.D. in Behavioral Science", "DBT Certified", "7+ years experience"],
    specialties: ["OCD", "Phobias", "Self-Esteem"],
    pricePerSession: 1600,
    rating: 4.7,
    reviewCount: 148,
    availableSlots: [
      { day: "Tuesday", times: ["10:00 AM", "12:00 PM", "3:00 PM"] },
      { day: "Thursday", times: ["9:00 AM", "2:00 PM", "5:00 PM"] },
    ],
    languages: ["Marathi", "Hindi", "English", "Gujarati"],
    bio: "Dr. Malhotra uses Dialectical Behavior Therapy and exposure techniques to help clients manage OCD, overcome phobias, and build unshakable self-esteem.",
    image: "/therapists/ritu.jpg",
  },
  {
    id: "18",
    name: "Dr. Sanjay Nambiar",
    title: "Neuropsychologist",
    qualifications: ["Ph.D. in Neuropsychology", "Cognitive Rehab Certified", "10+ years experience"],
    specialties: ["Brain Injury Rehab", "Memory Disorders", "Learning Disabilities"],
    pricePerSession: 2600,
    rating: 4.8,
    reviewCount: 98,
    availableSlots: [
      { day: "Monday", times: ["9:00 AM", "11:00 AM"] },
      { day: "Wednesday", times: ["10:00 AM", "2:00 PM"] },
      { day: "Friday", times: ["9:00 AM", "12:00 PM", "3:00 PM"] },
    ],
    languages: ["Malayalam", "English", "Tamil", "Kannada"],
    bio: "Dr. Nambiar is an expert in neuropsychological assessment and cognitive rehabilitation, helping patients with brain injuries and neurodevelopmental conditions regain their cognitive potential.",
    image: "/therapists/sanjay.jpg",
  },
]
