export interface Therapist {
  id: string
  name: string
  title: string
  qualifications: string[]
  specialties: string[]
  pricePerSession: number
  rating: number
  reviewCount: number
  availableSlots: {
    day: string
    times: string[]
  }[]
  languages: string[]
  bio: string
  image: string
}

export const therapists: Therapist[] = [
  // ===================== CLINICAL PSYCHOLOGISTS =====================
  {
    id: "1",
    name: "Dr. Sarah Mitchell",
    title: "Clinical Psychologist",
    qualifications: ["Ph.D. in Clinical Psychology", "Licensed CBT Practitioner", "15+ years experience"],
    specialties: ["Anxiety", "Depression", "Stress Management"],
    pricePerSession: 1500,
    rating: 4.9,
    reviewCount: 234,
    availableSlots: [
      { day: "Monday", times: ["9:00 AM", "11:00 AM", "2:00 PM", "4:00 PM"] },
      { day: "Wednesday", times: ["10:00 AM", "1:00 PM", "3:00 PM"] },
      { day: "Friday", times: ["9:00 AM", "11:00 AM", "2:00 PM"] },
    ],
    languages: ["English", "Hindi", "French"],
    bio: "Dr. Mitchell specializes in helping individuals overcome anxiety and depression using evidence-based approaches. Her warm and empathetic style creates a safe space for healing.",
    image: "/therapists/sarah.jpg",
  },
  {
    id: "9",
    name: "Dr. Fatima Khan",
    title: "Clinical Psychologist",
    qualifications: ["Ph.D. in Clinical Psychology", "CBT & DBT Certified", "10+ years experience"],
    specialties: ["Anxiety", "Self-Esteem", "Women's Mental Health"],
    pricePerSession: 1400,
    rating: 4.9,
    reviewCount: 267,
    availableSlots: [
      { day: "Monday", times: ["9:00 AM", "11:00 AM", "3:00 PM"] },
      { day: "Wednesday", times: ["10:00 AM", "1:00 PM", "4:00 PM"] },
      { day: "Friday", times: ["9:00 AM", "12:00 PM", "2:00 PM"] },
    ],
    languages: ["Urdu", "Hindi", "English", "Punjabi"],
    bio: "Dr. Khan focuses on women's mental health and self-esteem building, creating a safe and culturally sensitive environment for clients to explore their thoughts and emotions.",
    image: "/therapists/fatima.jpg",
  },
  {
    id: "11",
    name: "Dr. Meera Banerjee",
    title: "Clinical Psychologist",
    qualifications: ["Ph.D. in Clinical Psychology", "ACT Certified", "9+ years experience"],
    specialties: ["Anxiety", "Self-Esteem", "Work-Life Balance"],
    pricePerSession: 1300,
    rating: 4.8,
    reviewCount: 210,
    availableSlots: [
      { day: "Monday", times: ["9:00 AM", "11:00 AM", "3:00 PM"] },
      { day: "Thursday", times: ["10:00 AM", "1:00 PM", "4:00 PM"] },
      { day: "Saturday", times: ["10:00 AM", "12:00 PM"] },
    ],
    languages: ["Bengali", "English", "Hindi", "Tamil"],
    bio: "Dr. Banerjee uses Acceptance and Commitment Therapy to help clients overcome anxiety and build self-esteem through mindfulness and values-based living.",
    image: "/therapists/meera.jpg",
  },
  {
    id: "19",
    name: "Dr. Kavitha Suresh",
    title: "Clinical Psychologist",
    qualifications: ["Ph.D. in Clinical Psychology", "REBT Certified", "12+ years experience"],
    specialties: ["Depression", "Stress Management", "Self-Esteem"],
    pricePerSession: 1350,
    rating: 4.8,
    reviewCount: 195,
    availableSlots: [
      { day: "Tuesday", times: ["9:00 AM", "11:00 AM", "2:00 PM"] },
      { day: "Thursday", times: ["10:00 AM", "1:00 PM"] },
      { day: "Saturday", times: ["9:00 AM", "11:00 AM"] },
    ],
    languages: ["Malayalam", "English", "Kannada", "Tamil"],
    bio: "Dr. Suresh uses Rational Emotive Behavior Therapy to help clients challenge negative thinking patterns and develop healthier emotional responses to life challenges.",
    image: "/therapists/kavitha.jpg",
  },
  {
    id: "20",
    name: "Dr. Harpreet Gill",
    title: "Clinical Psychologist",
    qualifications: ["Ph.D. in Clinical Psychology", "Schema Therapy Certified", "8+ years experience"],
    specialties: ["Anxiety", "Depression", "Women's Mental Health"],
    pricePerSession: 1450,
    rating: 3.9,
    reviewCount: 78,
    availableSlots: [
      { day: "Monday", times: ["10:00 AM", "1:00 PM", "4:00 PM"] },
      { day: "Wednesday", times: ["9:00 AM", "12:00 PM", "3:00 PM"] },
      { day: "Friday", times: ["10:00 AM", "2:00 PM"] },
    ],
    languages: ["Punjabi", "Hindi", "English", "Urdu"],
    bio: "Dr. Gill uses Schema Therapy to help clients identify and change deep-rooted emotional patterns. She creates a nurturing space especially for women dealing with anxiety and depression.",
    image: "/therapists/harpreet.jpg",
  },
  {
    id: "21",
    name: "Dr. Teresa Gomes",
    title: "Clinical Psychologist",
    qualifications: ["Psy.D. in Clinical Psychology", "Narrative Therapy Certified", "11+ years experience"],
    specialties: ["Stress Management", "Self-Esteem", "Work-Life Balance"],
    pricePerSession: 1550,
    rating: 4.8,
    reviewCount: 202,
    availableSlots: [
      { day: "Tuesday", times: ["10:00 AM", "12:00 PM", "3:00 PM"] },
      { day: "Thursday", times: ["9:00 AM", "11:00 AM", "2:00 PM"] },
    ],
    languages: ["Spanish", "English", "French", "Gujarati"],
    bio: "Dr. Gomes helps clients rewrite their personal narratives, replacing self-doubt with empowerment using evidence-based narrative therapy techniques.",
    image: "/therapists/teresa.jpg",
  },
  {
    id: "22",
    name: "Dr. Rohit Hegde",
    title: "Clinical Psychologist",
    qualifications: ["Ph.D. in Clinical Psychology", "CFT Certified", "9+ years experience"],
    specialties: ["Depression", "Anxiety", "Self-Esteem"],
    pricePerSession: 1400,
    rating: 3.5,
    reviewCount: 68,
    availableSlots: [
      { day: "Monday", times: ["9:00 AM", "12:00 PM"] },
      { day: "Wednesday", times: ["10:00 AM", "2:00 PM", "4:00 PM"] },
      { day: "Saturday", times: ["10:00 AM", "12:00 PM"] },
    ],
    languages: ["Kannada", "English", "Telugu", "Marathi"],
    bio: "Dr. Hegde uses Compassion-Focused Therapy to help clients develop self-compassion, reduce self-criticism, and build emotional resilience against depression and anxiety.",
    image: "/therapists/rohit.jpg",
  },

  // ===================== PSYCHIATRISTS =====================
  {
    id: "2",
    name: "Dr. James Chen",
    title: "Psychiatrist",
    qualifications: ["M.D. in Psychiatry", "Board Certified", "12+ years experience"],
    specialties: ["Mood Disorders", "PTSD", "Medication Management"],
    pricePerSession: 2500,
    rating: 4.8,
    reviewCount: 189,
    availableSlots: [
      { day: "Tuesday", times: ["10:00 AM", "12:00 PM", "3:00 PM"] },
      { day: "Thursday", times: ["9:00 AM", "11:00 AM", "1:00 PM", "4:00 PM"] },
    ],
    languages: ["English", "Tamil", "Kannada"],
    bio: "Dr. Chen combines medication management with therapeutic techniques to provide comprehensive mental health care. He believes in treating the whole person, not just symptoms.",
    image: "/therapists/james.jpg",
  },
  {
    id: "23",
    name: "Dr. Neha Kapoor",
    title: "Psychiatrist",
    qualifications: ["M.D. in Psychiatry", "Board Certified", "14+ years experience"],
    specialties: ["Mood Disorders", "Medication Management", "Depression"],
    pricePerSession: 2400,
    rating: 4.9,
    reviewCount: 215,
    availableSlots: [
      { day: "Monday", times: ["10:00 AM", "1:00 PM", "3:00 PM"] },
      { day: "Wednesday", times: ["9:00 AM", "11:00 AM", "2:00 PM"] },
      { day: "Friday", times: ["10:00 AM", "12:00 PM"] },
    ],
    languages: ["Hindi", "English", "Punjabi", "Urdu"],
    bio: "Dr. Kapoor is a compassionate psychiatrist who combines modern pharmacotherapy with holistic patient care, providing comprehensive treatment for mood disorders and depression.",
    image: "/therapists/neha.jpg",
  },
  {
    id: "24",
    name: "Dr. Sunil Menon",
    title: "Psychiatrist",
    qualifications: ["M.D. in Psychiatry", "Psychopharmacology Certified", "16+ years experience"],
    specialties: ["PTSD", "Mood Disorders", "Medication Management"],
    pricePerSession: 2600,
    rating: 4.8,
    reviewCount: 175,
    availableSlots: [
      { day: "Tuesday", times: ["9:00 AM", "11:00 AM", "2:00 PM"] },
      { day: "Thursday", times: ["10:00 AM", "1:00 PM", "4:00 PM"] },
      { day: "Saturday", times: ["10:00 AM", "12:00 PM"] },
    ],
    languages: ["Malayalam", "English", "Bengali", "Hindi"],
    bio: "Dr. Menon is a veteran psychiatrist with expertise in trauma-informed pharmacotherapy, helping patients manage PTSD and complex mood disorders with precision and empathy.",
    image: "/therapists/sunil.jpg",
  },
  {
    id: "25",
    name: "Dr. Ayesha Siddiqui",
    title: "Psychiatrist",
    qualifications: ["M.D. in Psychiatry", "Consultation-Liaison Certified", "10+ years experience"],
    specialties: ["Mood Disorders", "Depression", "Medication Management"],
    pricePerSession: 2300,
    rating: 3.8,
    reviewCount: 56,
    availableSlots: [
      { day: "Monday", times: ["9:00 AM", "12:00 PM", "3:00 PM"] },
      { day: "Wednesday", times: ["10:00 AM", "2:00 PM"] },
      { day: "Friday", times: ["9:00 AM", "11:00 AM", "1:00 PM"] },
    ],
    languages: ["Urdu", "Hindi", "English", "Gujarati", "Marathi"],
    bio: "Dr. Siddiqui provides culturally aware psychiatric care, blending medication management with supportive counseling to treat depression and mood disorders in diverse populations.",
    image: "/therapists/ayesha.jpg",
  },
  {
    id: "26",
    name: "Dr. Pablo Martinez",
    title: "Psychiatrist",
    qualifications: ["M.D. in Psychiatry", "Board Certified", "11+ years experience"],
    specialties: ["PTSD", "Medication Management", "Mood Disorders"],
    pricePerSession: 2700,
    rating: 4.8,
    reviewCount: 142,
    availableSlots: [
      { day: "Tuesday", times: ["10:00 AM", "1:00 PM"] },
      { day: "Thursday", times: ["9:00 AM", "11:00 AM", "3:00 PM"] },
    ],
    languages: ["Spanish", "English", "French", "Telugu"],
    bio: "Dr. Martinez specializes in PTSD pharmacotherapy and integrative psychiatric treatment for patients from multicultural backgrounds.",
    image: "/therapists/pablo.jpg",
  },

  // ===================== MARRIAGE & FAMILY THERAPISTS =====================
  {
    id: "3",
    name: "Dr. Emily Rodriguez",
    title: "Marriage & Family Therapist",
    qualifications: ["Ph.D. in Family Therapy", "LMFT Licensed", "10+ years experience"],
    specialties: ["Couples Therapy", "Family Dynamics", "Communication"],
    pricePerSession: 1200,
    rating: 4.9,
    reviewCount: 312,
    availableSlots: [
      { day: "Monday", times: ["10:00 AM", "2:00 PM", "5:00 PM"] },
      { day: "Tuesday", times: ["9:00 AM", "11:00 AM", "3:00 PM"] },
      { day: "Saturday", times: ["10:00 AM", "12:00 PM", "2:00 PM"] },
    ],
    languages: ["English", "Spanish", "Telugu"],
    bio: "Dr. Rodriguez helps families and couples build stronger connections through improved communication and understanding. She creates a judgment-free zone for all.",
    image: "/therapists/emily.jpg",
  },
  {
    id: "15",
    name: "Dr. Simran Kaur",
    title: "Marriage & Family Therapist",
    qualifications: ["Ph.D. in Family Psychology", "EFT Certified", "10+ years experience"],
    specialties: ["Couples Therapy", "Family Dynamics", "Women's Mental Health"],
    pricePerSession: 1400,
    rating: 4.9,
    reviewCount: 225,
    availableSlots: [
      { day: "Tuesday", times: ["9:00 AM", "11:00 AM", "3:00 PM"] },
      { day: "Thursday", times: ["10:00 AM", "1:00 PM", "4:00 PM"] },
      { day: "Saturday", times: ["10:00 AM", "12:00 PM", "2:00 PM"] },
    ],
    languages: ["Punjabi", "Hindi", "English", "Bengali"],
    bio: "Dr. Kaur specializes in Emotionally Focused Therapy to help couples and families rebuild trust, deepen bonds, and communicate more effectively.",
    image: "/therapists/simran.jpg",
  },
  {
    id: "27",
    name: "Dr. Rakesh Joshi",
    title: "Marriage & Family Therapist",
    qualifications: ["Ph.D. in Marriage & Family Therapy", "Gottman Certified", "13+ years experience"],
    specialties: ["Couples Therapy", "Communication", "Family Dynamics"],
    pricePerSession: 1300,
    rating: 4.8,
    reviewCount: 194,
    availableSlots: [
      { day: "Monday", times: ["10:00 AM", "12:00 PM", "3:00 PM"] },
      { day: "Wednesday", times: ["9:00 AM", "11:00 AM", "2:00 PM"] },
      { day: "Friday", times: ["10:00 AM", "1:00 PM"] },
    ],
    languages: ["Marathi", "Hindi", "English", "Gujarati", "Kannada"],
    bio: "Dr. Joshi uses the Gottman Method to help couples strengthen their relationships through research-backed communication and conflict resolution strategies.",
    image: "/therapists/rakesh.jpg",
  },
  {
    id: "28",
    name: "Dr. Amina Bashir",
    title: "Marriage & Family Therapist",
    qualifications: ["Ph.D. in Family Psychology", "Systemic Therapy Certified", "9+ years experience"],
    specialties: ["Family Dynamics", "Couples Therapy", "Communication"],
    pricePerSession: 1250,
    rating: 3.6,
    reviewCount: 47,
    availableSlots: [
      { day: "Tuesday", times: ["10:00 AM", "1:00 PM", "4:00 PM"] },
      { day: "Thursday", times: ["9:00 AM", "12:00 PM", "3:00 PM"] },
    ],
    languages: ["Urdu", "English", "Malayalam", "Tamil"],
    bio: "Dr. Bashir takes a systemic approach to family therapy, helping families understand intergenerational patterns and build healthier relational dynamics.",
    image: "/therapists/amina.jpg",
  },

  // ===================== BEHAVIORAL THERAPISTS =====================
  {
    id: "4",
    name: "Dr. Michael Thompson",
    title: "Behavioral Therapist",
    qualifications: ["Psy.D. in Behavioral Psychology", "ABA Certified", "8+ years experience"],
    specialties: ["OCD", "Phobias", "Behavioral Issues"],
    pricePerSession: 1800,
    rating: 3.4,
    reviewCount: 56,
    availableSlots: [
      { day: "Wednesday", times: ["9:00 AM", "11:00 AM", "1:00 PM", "3:00 PM"] },
      { day: "Thursday", times: ["10:00 AM", "2:00 PM", "4:00 PM"] },
      { day: "Friday", times: ["9:00 AM", "12:00 PM"] },
    ],
    languages: ["English", "Hindi", "Marathi"],
    bio: "Dr. Thompson uses proven behavioral techniques to help clients overcome fears, compulsions, and unwanted behaviors. He focuses on practical, actionable strategies.",
    image: "/therapists/michael.jpg",
  },
  {
    id: "17",
    name: "Dr. Ritu Malhotra",
    title: "Behavioral Therapist",
    qualifications: ["Psy.D. in Behavioral Science", "DBT Certified", "7+ years experience"],
    specialties: ["OCD", "Phobias", "Self-Esteem"],
    pricePerSession: 1600,
    rating: 4.2,
    reviewCount: 98,
    availableSlots: [
      { day: "Tuesday", times: ["10:00 AM", "12:00 PM", "3:00 PM"] },
      { day: "Thursday", times: ["9:00 AM", "2:00 PM", "5:00 PM"] },
    ],
    languages: ["Marathi", "Hindi", "English", "Gujarati", "Punjabi"],
    bio: "Dr. Malhotra uses Dialectical Behavior Therapy and exposure techniques to help clients manage OCD, overcome phobias, and build unshakable self-esteem.",
    image: "/therapists/ritu.jpg",
  },
  {
    id: "29",
    name: "Dr. Naveen Kumar",
    title: "Behavioral Therapist",
    qualifications: ["Psy.D. in Applied Behavior Analysis", "BCBA Certified", "10+ years experience"],
    specialties: ["Behavioral Issues", "OCD", "Phobias"],
    pricePerSession: 1700,
    rating: 4.8,
    reviewCount: 185,
    availableSlots: [
      { day: "Monday", times: ["9:00 AM", "11:00 AM", "2:00 PM"] },
      { day: "Wednesday", times: ["10:00 AM", "1:00 PM", "4:00 PM"] },
      { day: "Friday", times: ["9:00 AM", "12:00 PM", "3:00 PM"] },
    ],
    languages: ["Telugu", "English", "Kannada", "Tamil", "Bengali"],
    bio: "Dr. Kumar applies Board Certified Behavior Analysis techniques to help adults and adolescents overcome behavioral challenges, compulsive disorders, and irrational fears.",
    image: "/therapists/naveen.jpg",
  },
  {
    id: "30",
    name: "Dr. Sophie Leclair",
    title: "Behavioral Therapist",
    qualifications: ["Psy.D. in Behavioral Psychology", "ERP Certified", "8+ years experience"],
    specialties: ["OCD", "Phobias", "Behavioral Issues"],
    pricePerSession: 1650,
    rating: 3.2,
    reviewCount: 37,
    availableSlots: [
      { day: "Tuesday", times: ["10:00 AM", "2:00 PM", "4:00 PM"] },
      { day: "Thursday", times: ["9:00 AM", "11:00 AM", "3:00 PM"] },
      { day: "Saturday", times: ["10:00 AM", "12:00 PM"] },
    ],
    languages: ["French", "English", "Spanish", "Malayalam", "Urdu"],
    bio: "Dr. Leclair specializes in Exposure and Response Prevention therapy, helping clients gradually face their fears and break free from OCD cycles.",
    image: "/therapists/sophie.jpg",
  },

  // ===================== TRAUMA SPECIALISTS =====================
  {
    id: "5",
    name: "Dr. Aisha Patel",
    title: "Trauma Specialist",
    qualifications: ["Ph.D. in Trauma Psychology", "EMDR Certified", "14+ years experience"],
    specialties: ["Trauma", "PTSD", "Grief & Loss"],
    pricePerSession: 2000,
    rating: 4.9,
    reviewCount: 278,
    availableSlots: [
      { day: "Monday", times: ["11:00 AM", "2:00 PM", "4:00 PM"] },
      { day: "Tuesday", times: ["9:00 AM", "1:00 PM", "3:00 PM"] },
      { day: "Thursday", times: ["10:00 AM", "12:00 PM", "2:00 PM"] },
    ],
    languages: ["English", "Hindi", "Gujarati", "Urdu", "Punjabi"],
    bio: "Dr. Patel specializes in trauma recovery using EMDR and other evidence-based approaches. She provides a compassionate space for healing from life's most difficult experiences.",
    image: "/therapists/aisha.jpg",
  },
  {
    id: "12",
    name: "Dr. Carlos Fernandez",
    title: "Trauma Specialist",
    qualifications: ["Psy.D. in Clinical Psychology", "EMDR & Somatic Therapy Certified", "11+ years experience"],
    specialties: ["Trauma", "Grief & Loss", "PTSD"],
    pricePerSession: 1900,
    rating: 4.9,
    reviewCount: 176,
    availableSlots: [
      { day: "Tuesday", times: ["9:00 AM", "12:00 PM", "3:00 PM"] },
      { day: "Wednesday", times: ["10:00 AM", "2:00 PM", "5:00 PM"] },
      { day: "Friday", times: ["9:00 AM", "11:00 AM"] },
    ],
    languages: ["Spanish", "English", "French"],
    bio: "Dr. Fernandez is a bilingual trauma specialist who combines EMDR with somatic experiencing to guide clients through healing from deep-seated trauma and grief.",
    image: "/therapists/carlos.jpg",
  },
  {
    id: "31",
    name: "Dr. Deepa Venkatesh",
    title: "Trauma Specialist",
    qualifications: ["Ph.D. in Trauma Psychology", "Somatic Experiencing Certified", "10+ years experience"],
    specialties: ["Trauma", "PTSD", "Grief & Loss"],
    pricePerSession: 1850,
    rating: 4.8,
    reviewCount: 201,
    availableSlots: [
      { day: "Monday", times: ["9:00 AM", "11:00 AM", "3:00 PM"] },
      { day: "Wednesday", times: ["10:00 AM", "1:00 PM"] },
      { day: "Friday", times: ["9:00 AM", "12:00 PM", "2:00 PM"] },
    ],
    languages: ["Tamil", "English", "Kannada", "Telugu", "Malayalam"],
    bio: "Dr. Venkatesh combines somatic experiencing with narrative therapy to help survivors of trauma reconnect with their bodies and reclaim their stories.",
    image: "/therapists/deepa.jpg",
  },
  {
    id: "32",
    name: "Dr. Jasleen Bhatia",
    title: "Trauma Specialist",
    qualifications: ["Ph.D. in Clinical Psychology", "CPT & EMDR Certified", "12+ years experience"],
    specialties: ["Trauma", "Grief & Loss", "PTSD"],
    pricePerSession: 2100,
    rating: 4.9,
    reviewCount: 189,
    availableSlots: [
      { day: "Tuesday", times: ["10:00 AM", "12:00 PM", "3:00 PM"] },
      { day: "Thursday", times: ["9:00 AM", "11:00 AM", "2:00 PM"] },
      { day: "Saturday", times: ["10:00 AM", "1:00 PM"] },
    ],
    languages: ["Punjabi", "Hindi", "English", "Bengali", "Marathi"],
    bio: "Dr. Bhatia uses Cognitive Processing Therapy alongside EMDR to provide dual-approach trauma treatment, specializing in complex trauma and prolonged grief.",
    image: "/therapists/jasleen.jpg",
  },

  // ===================== MINDFULNESS THERAPISTS =====================
  {
    id: "6",
    name: "Dr. David Kim",
    title: "Mindfulness Therapist",
    qualifications: ["Ph.D. in Psychology", "MBSR Certified", "9+ years experience"],
    specialties: ["Mindfulness", "Stress", "Work-Life Balance"],
    pricePerSession: 1000,
    rating: 4.8,
    reviewCount: 201,
    availableSlots: [
      { day: "Tuesday", times: ["8:00 AM", "10:00 AM", "4:00 PM", "6:00 PM"] },
      { day: "Wednesday", times: ["9:00 AM", "11:00 AM", "3:00 PM"] },
      { day: "Friday", times: ["10:00 AM", "2:00 PM", "4:00 PM"] },
    ],
    languages: ["English", "Bengali", "Malayalam", "Hindi"],
    bio: "Dr. Kim integrates mindfulness-based approaches with traditional therapy to help clients find balance, reduce stress, and cultivate inner peace in their daily lives.",
    image: "/therapists/david.jpg",
  },
  {
    id: "16",
    name: "Dr. Laurent Dupont",
    title: "Mindfulness Therapist",
    qualifications: ["Ph.D. in Psychology", "MBCT Certified", "12+ years experience"],
    specialties: ["Mindfulness", "Stress", "Depression"],
    pricePerSession: 1700,
    rating: 4.8,
    reviewCount: 189,
    availableSlots: [
      { day: "Monday", times: ["10:00 AM", "2:00 PM"] },
      { day: "Wednesday", times: ["9:00 AM", "11:00 AM", "3:00 PM"] },
      { day: "Friday", times: ["10:00 AM", "1:00 PM", "4:00 PM"] },
    ],
    languages: ["French", "English", "Spanish"],
    bio: "Dr. Dupont integrates Mindfulness-Based Cognitive Therapy with traditional approaches, helping clients break free from cycles of depression and chronic stress.",
    image: "/therapists/laurent.jpg",
  },
  {
    id: "33",
    name: "Dr. Pooja Nair",
    title: "Mindfulness Therapist",
    qualifications: ["Ph.D. in Contemplative Psychology", "MBSR & Yoga Therapy Certified", "8+ years experience"],
    specialties: ["Mindfulness", "Stress", "Work-Life Balance"],
    pricePerSession: 1100,
    rating: 4.9,
    reviewCount: 220,
    availableSlots: [
      { day: "Monday", times: ["9:00 AM", "11:00 AM", "3:00 PM"] },
      { day: "Thursday", times: ["10:00 AM", "1:00 PM", "4:00 PM"] },
      { day: "Saturday", times: ["9:00 AM", "11:00 AM"] },
    ],
    languages: ["Malayalam", "English", "Tamil", "Kannada", "Telugu"],
    bio: "Dr. Pooja Nair blends yoga therapy with mindfulness-based stress reduction to help clients achieve deep relaxation, emotional balance, and lasting inner peace.",
    image: "/therapists/poojan.jpg",
  },
  {
    id: "34",
    name: "Dr. Gurpreet Singh",
    title: "Mindfulness Therapist",
    qualifications: ["Ph.D. in Health Psychology", "MBCT Certified", "10+ years experience"],
    specialties: ["Mindfulness", "Depression", "Stress"],
    pricePerSession: 1200,
    rating: 4.8,
    reviewCount: 174,
    availableSlots: [
      { day: "Tuesday", times: ["9:00 AM", "12:00 PM", "3:00 PM"] },
      { day: "Thursday", times: ["10:00 AM", "2:00 PM"] },
      { day: "Friday", times: ["9:00 AM", "11:00 AM", "1:00 PM"] },
    ],
    languages: ["Punjabi", "Hindi", "English", "Urdu", "Gujarati"],
    bio: "Dr. Singh combines mindfulness meditation with cognitive therapy to help clients break the cycle of recurring depression and chronic stress, promoting lasting well-being.",
    image: "/therapists/gurpreet.jpg",
  },
  {
    id: "35",
    name: "Dr. Swati Deshmukh",
    title: "Mindfulness Therapist",
    qualifications: ["Ph.D. in Clinical Psychology", "ACT & MBSR Certified", "7+ years experience"],
    specialties: ["Stress", "Work-Life Balance", "Mindfulness"],
    pricePerSession: 1150,
    rating: 3.7,
    reviewCount: 56,
    availableSlots: [
      { day: "Monday", times: ["10:00 AM", "1:00 PM"] },
      { day: "Wednesday", times: ["9:00 AM", "11:00 AM", "3:00 PM"] },
      { day: "Saturday", times: ["10:00 AM", "12:00 PM", "2:00 PM"] },
    ],
    languages: ["Marathi", "Hindi", "English", "Bengali"],
    bio: "Dr. Deshmukh integrates Acceptance and Commitment Therapy with mindfulness practices to help busy professionals manage stress and find meaningful work-life balance.",
    image: "/therapists/swati.jpg",
  },

  // ===================== CHILD PSYCHOLOGISTS =====================
  {
    id: "7",
    name: "Dr. Priya Sharma",
    title: "Child Psychologist",
    qualifications: ["Ph.D. in Child Psychology", "Play Therapy Certified", "11+ years experience"],
    specialties: ["Child Behavior", "ADHD", "Learning Disabilities"],
    pricePerSession: 1600,
    rating: 4.8,
    reviewCount: 198,
    availableSlots: [
      { day: "Monday", times: ["10:00 AM", "12:00 PM", "3:00 PM"] },
      { day: "Wednesday", times: ["9:00 AM", "11:00 AM", "2:00 PM"] },
      { day: "Saturday", times: ["10:00 AM", "12:00 PM"] },
    ],
    languages: ["Hindi", "English", "Punjabi", "Gujarati"],
    bio: "Dr. Sharma specializes in child and adolescent mental health, using play therapy and creative approaches to help young minds thrive and overcome behavioral challenges.",
    image: "/therapists/priya.jpg",
  },
  {
    id: "13",
    name: "Dr. Ananya Iyer",
    title: "Child Psychologist",
    qualifications: ["Ph.D. in Developmental Psychology", "CBT for Children Certified", "8+ years experience"],
    specialties: ["Child Behavior", "ADHD", "Anxiety"],
    pricePerSession: 1500,
    rating: 3.3,
    reviewCount: 43,
    availableSlots: [
      { day: "Monday", times: ["10:00 AM", "1:00 PM", "4:00 PM"] },
      { day: "Wednesday", times: ["9:00 AM", "11:00 AM"] },
      { day: "Friday", times: ["10:00 AM", "2:00 PM", "4:00 PM"] },
    ],
    languages: ["Tamil", "English", "Malayalam", "Hindi", "Kannada"],
    bio: "Dr. Iyer is passionate about helping children navigate emotional and behavioral challenges. She uses creative, age-appropriate CBT techniques to empower young clients.",
    image: "/therapists/ananya.jpg",
  },
  {
    id: "36",
    name: "Dr. Seema Roy",
    title: "Child Psychologist",
    qualifications: ["Ph.D. in Child & Adolescent Psychology", "Filial Therapy Certified", "9+ years experience"],
    specialties: ["ADHD", "Learning Disabilities", "Child Behavior"],
    pricePerSession: 1550,
    rating: 4.8,
    reviewCount: 182,
    availableSlots: [
      { day: "Tuesday", times: ["10:00 AM", "12:00 PM", "3:00 PM"] },
      { day: "Thursday", times: ["9:00 AM", "11:00 AM", "2:00 PM"] },
      { day: "Saturday", times: ["10:00 AM", "12:00 PM"] },
    ],
    languages: ["Bengali", "English", "Hindi", "Urdu", "Marathi"],
    bio: "Dr. Roy combines filial therapy with behavioral techniques to empower both children and their parents, creating lasting positive changes in the family unit.",
    image: "/therapists/seema.jpg",
  },
  {
    id: "37",
    name: "Dr. Karthik Raman",
    title: "Child Psychologist",
    qualifications: ["Psy.D. in Child Psychology", "Sandplay Therapy Certified", "10+ years experience"],
    specialties: ["Child Behavior", "ADHD", "Learning Disabilities"],
    pricePerSession: 1450,
    rating: 4.0,
    reviewCount: 72,
    availableSlots: [
      { day: "Monday", times: ["9:00 AM", "11:00 AM"] },
      { day: "Wednesday", times: ["10:00 AM", "1:00 PM", "4:00 PM"] },
      { day: "Friday", times: ["10:00 AM", "12:00 PM", "3:00 PM"] },
    ],
    languages: ["Telugu", "English", "Kannada", "Spanish", "French"],
    bio: "Dr. Raman uses sandplay therapy and art-based interventions to help children express and process emotions they cannot yet put into words.",
    image: "/therapists/karthik.jpg",
  },

  // ===================== ADDICTION COUNSELORS =====================
  {
    id: "8",
    name: "Dr. Rajesh Nair",
    title: "Addiction Counselor",
    qualifications: ["M.D. in Psychiatry", "Addiction Medicine Certified", "16+ years experience"],
    specialties: ["Substance Abuse", "Addiction Recovery", "Relapse Prevention"],
    pricePerSession: 2200,
    rating: 4.1,
    reviewCount: 85,
    availableSlots: [
      { day: "Tuesday", times: ["9:00 AM", "11:00 AM", "2:00 PM", "5:00 PM"] },
      { day: "Thursday", times: ["10:00 AM", "1:00 PM", "3:00 PM"] },
      { day: "Friday", times: ["9:00 AM", "11:00 AM"] },
    ],
    languages: ["Malayalam", "English", "Tamil", "Hindi", "Kannada"],
    bio: "Dr. Nair brings extensive experience in addiction recovery, combining medical expertise with compassionate counseling to support patients through every stage of their recovery journey.",
    image: "/therapists/rajesh.jpg",
  },
  {
    id: "14",
    name: "Dr. Vikram Desai",
    title: "Addiction Counselor",
    qualifications: ["M.D. in Psychiatry", "Dual Diagnosis Certified", "14+ years experience"],
    specialties: ["Substance Abuse", "Addiction Recovery", "Depression"],
    pricePerSession: 2100,
    rating: 4.8,
    reviewCount: 134,
    availableSlots: [
      { day: "Monday", times: ["9:00 AM", "12:00 PM"] },
      { day: "Wednesday", times: ["10:00 AM", "2:00 PM", "4:00 PM"] },
      { day: "Thursday", times: ["9:00 AM", "11:00 AM", "3:00 PM"] },
    ],
    languages: ["Gujarati", "Hindi", "English", "Marathi", "Punjabi"],
    bio: "Dr. Desai combines psychiatric expertise with compassionate counseling to help clients recover from addiction and co-occurring mental health conditions.",
    image: "/therapists/vikram.jpg",
  },
  {
    id: "38",
    name: "Dr. Tariq Hussain",
    title: "Addiction Counselor",
    qualifications: ["M.D. in Addiction Psychiatry", "ASAM Certified", "13+ years experience"],
    specialties: ["Substance Abuse", "Relapse Prevention", "Addiction Recovery"],
    pricePerSession: 2000,
    rating: 4.8,
    reviewCount: 161,
    availableSlots: [
      { day: "Monday", times: ["10:00 AM", "1:00 PM", "3:00 PM"] },
      { day: "Wednesday", times: ["9:00 AM", "11:00 AM", "2:00 PM"] },
      { day: "Friday", times: ["10:00 AM", "12:00 PM"] },
    ],
    languages: ["Urdu", "English", "Hindi", "Bengali", "Telugu"],
    bio: "Dr. Hussain provides evidence-based addiction treatment using motivational interviewing and relapse prevention therapy, with a focus on culturally sensitive care.",
    image: "/therapists/tariq.jpg",
  },
  {
    id: "39",
    name: "Dr. Marie Beaumont",
    title: "Addiction Counselor",
    qualifications: ["Psy.D. in Addiction Psychology", "MI Certified", "9+ years experience"],
    specialties: ["Addiction Recovery", "Substance Abuse", "Relapse Prevention"],
    pricePerSession: 1900,
    rating: 3.0,
    reviewCount: 28,
    availableSlots: [
      { day: "Tuesday", times: ["9:00 AM", "12:00 PM", "3:00 PM"] },
      { day: "Thursday", times: ["10:00 AM", "1:00 PM", "4:00 PM"] },
      { day: "Saturday", times: ["10:00 AM", "12:00 PM"] },
    ],
    languages: ["French", "English", "Spanish", "Punjabi"],
    bio: "Dr. Beaumont uses motivational interviewing and harm-reduction strategies to meet clients where they are on their recovery journey, supporting lasting change without judgment.",
    image: "/therapists/marie.jpg",
  },

  // ===================== NEUROPSYCHOLOGISTS =====================
  {
    id: "10",
    name: "Dr. Arjun Reddy",
    title: "Neuropsychologist",
    qualifications: ["Ph.D. in Neuropsychology", "Board Certified", "13+ years experience"],
    specialties: ["Brain Injury Rehab", "Memory Disorders", "Cognitive Assessment"],
    pricePerSession: 2800,
    rating: 4.8,
    reviewCount: 112,
    availableSlots: [
      { day: "Tuesday", times: ["10:00 AM", "2:00 PM"] },
      { day: "Thursday", times: ["9:00 AM", "11:00 AM", "3:00 PM"] },
    ],
    languages: ["Telugu", "English", "Kannada", "Hindi"],
    bio: "Dr. Reddy is a leading neuropsychologist specializing in cognitive rehabilitation and assessment, helping patients recover cognitive functions after brain injuries.",
    image: "/therapists/arjun.jpg",
  },
  {
    id: "18",
    name: "Dr. Sanjay Nambiar",
    title: "Neuropsychologist",
    qualifications: ["Ph.D. in Neuropsychology", "Cognitive Rehab Certified", "10+ years experience"],
    specialties: ["Brain Injury Rehab", "Memory Disorders", "Learning Disabilities"],
    pricePerSession: 2600,
    rating: 4.8,
    reviewCount: 98,
    availableSlots: [
      { day: "Monday", times: ["9:00 AM", "11:00 AM"] },
      { day: "Wednesday", times: ["10:00 AM", "2:00 PM"] },
      { day: "Friday", times: ["9:00 AM", "12:00 PM", "3:00 PM"] },
    ],
    languages: ["Malayalam", "English", "Tamil", "Kannada"],
    bio: "Dr. Nambiar is an expert in neuropsychological assessment and cognitive rehabilitation, helping patients with brain injuries and neurodevelopmental conditions regain their cognitive potential.",
    image: "/therapists/sanjay.jpg",
  },
  {
    id: "40",
    name: "Dr. Mandeep Oberoi",
    title: "Neuropsychologist",
    qualifications: ["Ph.D. in Neuropsychology", "Pediatric Neuropsychology Certified", "11+ years experience"],
    specialties: ["Cognitive Assessment", "Memory Disorders", "Brain Injury Rehab"],
    pricePerSession: 2700,
    rating: 4.9,
    reviewCount: 135,
    availableSlots: [
      { day: "Monday", times: ["10:00 AM", "1:00 PM", "3:00 PM"] },
      { day: "Wednesday", times: ["9:00 AM", "11:00 AM", "2:00 PM"] },
      { day: "Thursday", times: ["10:00 AM", "12:00 PM"] },
    ],
    languages: ["Punjabi", "Hindi", "English", "Urdu", "Bengali"],
    bio: "Dr. Oberoi specializes in both adult and pediatric neuropsychological evaluations, providing detailed cognitive assessments and personalized rehabilitation programs.",
    image: "/therapists/mandeep.jpg",
  },
  {
    id: "41",
    name: "Dr. Leena Bose",
    title: "Neuropsychologist",
    qualifications: ["Ph.D. in Clinical Neuropsychology", "Board Certified", "12+ years experience"],
    specialties: ["Brain Injury Rehab", "Cognitive Assessment", "Memory Disorders"],
    pricePerSession: 2500,
    rating: 4.8,
    reviewCount: 118,
    availableSlots: [
      { day: "Tuesday", times: ["9:00 AM", "11:00 AM", "2:00 PM"] },
      { day: "Friday", times: ["10:00 AM", "12:00 PM", "3:00 PM"] },
      { day: "Saturday", times: ["10:00 AM", "12:00 PM"] },
    ],
    languages: ["Bengali", "English", "Hindi", "Marathi", "Gujarati"],
    bio: "Dr. Bose provides comprehensive neuropsychological testing and brain injury rehabilitation programs tailored to each patient's unique cognitive profile and recovery goals.",
    image: "/therapists/leena.jpg",
  },
  {
    id: "42",
    name: "Dr. Rafael Ortiz",
    title: "Neuropsychologist",
    qualifications: ["Ph.D. in Neuropsychology", "Geriatric Neuropsych Certified", "14+ years experience"],
    specialties: ["Memory Disorders", "Cognitive Assessment", "Brain Injury Rehab"],
    pricePerSession: 2900,
    rating: 4.8,
    reviewCount: 105,
    availableSlots: [
      { day: "Monday", times: ["9:00 AM", "12:00 PM"] },
      { day: "Wednesday", times: ["10:00 AM", "1:00 PM", "4:00 PM"] },
      { day: "Thursday", times: ["9:00 AM", "11:00 AM"] },
    ],
    languages: ["Spanish", "English", "French", "Telugu", "Tamil"],
    bio: "Dr. Ortiz specializes in geriatric neuropsychology, helping older adults with memory disorders and age-related cognitive decline through targeted assessment and rehabilitation.",
    image: "/therapists/rafael.jpg",
  },
  {
    id: "43",
    name: "Dr. Nisha Agarwal",
    title: "Neuropsychologist",
    qualifications: ["Ph.D. in Neuropsychology", "Neurofeedback Certified", "9+ years experience"],
    specialties: ["Cognitive Assessment", "Brain Injury Rehab", "Memory Disorders"],
    pricePerSession: 2650,
    rating: 3.1,
    reviewCount: 31,
    availableSlots: [
      { day: "Tuesday", times: ["10:00 AM", "1:00 PM", "3:00 PM"] },
      { day: "Thursday", times: ["9:00 AM", "12:00 PM", "2:00 PM"] },
    ],
    languages: ["Marathi", "Hindi", "English", "Malayalam", "Gujarati"],
    bio: "Dr. Agarwal combines traditional neuropsychological assessment with cutting-edge neurofeedback therapy to optimize brain function and accelerate cognitive recovery.",
    image: "/therapists/nisha.jpg",
  },
]
